# Generated by Django 3.1.1 on 2020-09-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0002_auto_20200912_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.IntegerField(blank=True, null=True)),
                ('street_address', models.CharField(max_length=200)),
                ('postal_address', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
