# Generated by Django 3.1.1 on 2020-09-15 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyManagement', '0001_initial'),
        ('StudentManagement', '0004_auto_20200915_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FacultyManagement.advisor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentManagement.address'),
        ),
    ]
