# Generated by Django 3.1.1 on 2020-09-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0006_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='images/aaaaaaaa.jpg', null=True, upload_to='images/students'),
        ),
    ]
