conn sys as sysdba ;

create user delwar identified by delwar123 ;

create user ibcs identified by ibcs123 ;
grant create session to delwar;
grant create session to ibcs;
grant create table to delwar ;
grant create table to ibcs;
grant unlimited tablespace to delwar ;
grant unlimited tablespace to ibcs ;
grant select on employees to delwar ;
grant update on hr.employees to delwar ;

REVOKE create session from delwar, ibcs ;
REVOKE create table from delwar, ibcs ;
REVOKE select, update on hr.employees from delwar ;

create role my_role ;
grant create session to my_role;
grant create table to my_role ;
grant select, update, insert on hr.employees to my_role ;
grant select, delete on hr.departments to my_role ;

grant my_role to delwar, ibcs;

REVOKE select on hr.employees from my_role ;

drop user ibcs ;

alter user delwar identified by delwar321 ;

alter user delwar ACCOUNT lock ;

alter user delwar ACCOUNT unlock ;

select PRIVILEGE from ROLE_SYS_PRIVS where role='MY_ROLE';

SELECT PRIVILEGE, TABLE_NAME FROM ROLE_TAB_PRIVS WHERE ROLE='MY_ROLE'


select PRIVILEGE, TO_CHAR(NULL) TABLE_NAME from ROLE_SYS_PRIVS where role='MY_ROLE'
UNION
SELECT PRIVILEGE, TABLE_NAME FROM ROLE_TAB_PRIVS WHERE ROLE='MY_ROLE';

CREATE TABLE TAB_EMP (ID NUMBER, NAME VARCHAR2(50), SAL NUMBER) ;
CREATE TABLE TAB_JOBS (ID NUMBER, NAME VARCHAR2(50), JOBTITLE VARCHAR2(50)) ;
CREATE TABLE TAB_DEPTS (ID NUMBER, NAME VARCHAR2(50), DEPARTMENT VARCHAR2(50)) ;


INSERT  ALL INTO TAB_EMP VALUES(EMPLOYEE_ID, NAME, SALARY) 
			INTO TAB_JOBS VALUES(EMPLOYEE_ID, NAME, JOB_TITLE)
			INTO TAB_DEPTS VALUES(EMPLOYEE_ID, NAME, DEPARTMENT_NAME)
			
SELECT E.EMPLOYEE_ID, E.FIRST_NAME||E.LAST_NAME NAME, SALARY, J.JOB_TITLE, D.DEPARTMENT_NAME
   FROM  employees E JOIN JOBS J 
	ON E.JOB_ID=J.JOB_ID
	LEFT JOIN departments D
	ON E.DEPARTMENT_ID=D.DEPARTMENT_ID

DELETE TAB_EMP ;
DELETE TAB_JOBS;
DELETE TAB_DEPTS ;

INSERT  ALL 
WHEN SALARY>15000 THEN 
	INTO TAB_EMP VALUES(EMPLOYEE_ID, NAME, SALARY) 
WHEN JOB_ID IN ('IT_PROG','SA_MAN','ST_MAN') THEN
	INTO TAB_JOBS VALUES(EMPLOYEE_ID, NAME, JOB_TITLE)
WHEN DEPARTMENT_ID IN (20, 30, 90) THEN
	INTO TAB_DEPTS VALUES(EMPLOYEE_ID, NAME, DEPARTMENT_NAME)
			
SELECT E.EMPLOYEE_ID, E.FIRST_NAME||E.LAST_NAME NAME, SALARY, J.JOB_TITLE, D.DEPARTMENT_NAME,
		E.DEPARTMENT_ID, E.JOB_ID
   FROM  employees E JOIN JOBS J 
	ON E.JOB_ID=J.JOB_ID
	LEFT JOIN departments D
	ON E.DEPARTMENT_ID=D.DEPARTMENT_ID


INSERT  FIRST 
WHEN SALARY>15000 THEN 
	INTO TAB_EMP VALUES(EMPLOYEE_ID, NAME, SALARY) 
WHEN JOB_ID IN ('IT_PROG','SA_MAN','ST_MAN') THEN
	INTO TAB_JOBS VALUES(EMPLOYEE_ID, NAME, JOB_TITLE)
WHEN DEPARTMENT_ID IN (20, 30, 90) THEN
	INTO TAB_DEPTS VALUES(EMPLOYEE_ID, NAME, DEPARTMENT_NAME)
			
SELECT E.EMPLOYEE_ID, E.FIRST_NAME||E.LAST_NAME NAME, SALARY, J.JOB_TITLE, D.DEPARTMENT_NAME,
		E.DEPARTMENT_ID, E.JOB_ID
   FROM  employees E JOIN JOBS J 
	ON E.JOB_ID=J.JOB_ID
	LEFT JOIN departments D
	ON E.DEPARTMENT_ID=D.DEPARTMENT_ID

CREATE TABLE WEEKLY_SAL (WEEK_ID NUMBER, EMP_ID NUMBER, SAT NUMBER, SUN NUMBER, MON NUMBER, 
						TUE NUMBER, WED NUMBER, THU NUMBER) ;

INSERT INTO WEEKLY_SAL
VALUES (1, 100, 1200, 1500, 800, 450, 1400, 2000) ;

INSERT INTO WEEKLY_SAL
VALUES (1, 101, 1100, 1560, 850, 750, 1300, 500) ;

INSERT INTO WEEKLY_SAL
VALUES (1, 102, 1000, 1400, 700, 850, 1000, 2500) ;

CREATE TABLE SALES (WEEK_ID NUMBER, EMP_ID NUMBER, SALE NUMBER) ;

INSERT ALL 
INTO SALES VALUES (week_id, EMP_ID, SAT)  
INTO SALES VALUES (week_id, EMP_ID, SUN)
INTO SALES VALUES (week_id, EMP_ID, MON)
INTO SALES VALUES (week_id, EMP_ID, TUE)
INTO SALES VALUES (week_id, EMP_ID, WED)
INTO SALES VALUES (week_id, EMP_ID, THU)
SELECT EMP_ID, week_id, SAT, SUN, MON, TUE, WED, THU
FROM WEEKLY_SAL;


SELECT EMP_ID, FIRST_NAME||' '||LAST_NAME NAME,  SUM(SALE) SALE 
FROM SALES S, EMPLOYEES E 
WHERE S.EMP_ID=E.EMPLOYEE_ID
GROUP BY EMP_ID, FIRST_NAME||' '||LAST_NAME


CREATE TABLE EMP_HIST AS SELECT * FROM EMPLOYEES ;

DELETE EMP_HIST WHERE DEPARTMENT_ID=80 ;

UPDATE EMP_HIST SET SALARY=5000 WHERE DEPARTMENT_ID=50 ;

MERGE INTO EMP_HIST c
USING (SELECT * FROM EMPLOYEES ) e
ON (c.employee_id = e.employee_id)
WHEN MATCHED THEN
UPDATE SET
C.SALARY=E.SALARY
WHEN NOT MATCHED THEN
INSERT VALUES(e.employee_id, e.first_name, e.last_name,
e.email, e.phone_number, e.hire_date, e.job_id,
e.salary, e.commission_pct, e.manager_id, e.department_id);


DROP TABLE EMP_HIST

FLASHBACK TABLE EMP_HIST TO BEFORE DROP ;



SELECT EMPLOYEE_ID, LAST_NAME, J.JOB_TITLE, SALARY 
FROM EMPLOYEES E LEFT JOIN JOBs J 
ON E.JOB_ID=J.JOB_ID

SELECT EMPLOYEE_ID, LAST_NAME, J.JOB_TITLE, SALARY 
FROM EMPLOYEES E right JOIN JOBs J 
ON E.JOB_ID=J.JOB_ID

SELECT EMPLOYEE_ID, LAST_NAME, J.JOB_TITLE, SALARY, DEPARTMENT_NAME
FROM EMPLOYEES E LEFT JOIN JOBs J 
ON E.JOB_ID=J.JOB_ID
left join departments d
on e.department_id=d.DEPARTMENT_ID

SELECT EMPLOYEE_ID, LAST_NAME, J.JOB_TITLE, SALARY, DEPARTMENT_NAME
FROM EMPLOYEES E LEFT JOIN JOBs J 
ON E.JOB_ID=J.JOB_ID
right join departments d
on e.department_id=d.DEPARTMENT_ID

SELECT EMPLOYEE_ID, LAST_NAME, J.JOB_TITLE, SALARY, DEPARTMENT_NAME
FROM EMPLOYEES E LEFT JOIN JOBs J 
ON E.JOB_ID=J.JOB_ID
full join departments d
on e.department_id=d.DEPARTMENT_ID


SELECT EMPLOYEE_ID, LAST_NAME, J.JOB_TITLE, SALARY 
FROM EMPLOYEES E join JOBs J 
using (JOB_ID)


SELECT EMPLOYEE_ID, LAST_NAME, J.JOB_TITLE, SALARY, DEPARTMENT_NAME, city
FROM EMPLOYEES E LEFT JOIN JOBs J 
ON E.JOB_ID=J.JOB_ID
left join departments d
on e.department_id=d.DEPARTMENT_ID
left join locations l 
on d.location_id=l.location_id
where E.salary>10000
and j.job_id like '%MAN'